name: Run Postman Tests with Newman

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman and reporters
        run: |
          npm install -g newman newman-reporter-html newman-reporter-json

      - name: Run Postman tests
        run: |
          npm run test
